const database = {
    bands: [
        {
            id: 1,
            name: "The Rolling Stones",
            members: 4,
            genre: "Rock",
            yearFounded: 1962,
            image: "https://is5-ssl.mzstatic.com/image/thumb/Music123/v4/e5/53/4d/e5534d31-443d-3eb7-7d4d-e374259cfdd6/16ABKIM00055.rgb.jpg/600x600bb.jpg",
        },
        {
            id: 2,
            name: "Mumford & Sons",
            members: 4,
            genre: "Folk",
            yearFounded: 2007,
            image: "https://is3-ssl.mzstatic.com/image/thumb/Music/a8/b0/08/mzi.jdnhtolc.jpg/600x600bb.jpg",
        },
        {
            id: 3,
            name: "Fleetwood Mac",
            members: 5,
            genre: "Rock",
            image: "https://is5-ssl.mzstatic.com/image/thumb/Music4/v4/82/3a/d1/823ad171-70ec-63af-48e0-8d0eae935999/075992724128.jpg/600x600bb.jpg",
        },
        {
            id: 4,
            name: "The Avett Brothers",
            members: 3,
            genre: "Folk",
            yearFounded: 2000,
            image: "https://is5-ssl.mzstatic.com/image/thumb/Music/ab/02/91/mzi.ppnitdig.jpg/600x600bb.jpg",
        },
        {
            id: 5,
            name: "The Eagles",
            members: 6,
            genre: "Rock",
            yearFounded: 1971,
            image: "https://is4-ssl.mzstatic.com/image/thumb/Music125/v4/88/90/0d/88900ddb-b23e-c1e6-8147-20eb92340076/081227397128.jpg/600x600bb.jpg",
        },
        {
            id: 6,
            name: "Alison Krauss & Union Station",
            members: 5,
            genre: "Bluegrass",
            yearFounded: 1987,
            image: "https://is5-ssl.mzstatic.com/image/thumb/Music125/v4/8a/55/02/8a5502a7-b1e5-439f-64bc-5e0e9bbe12c1/19CRGIM11917.rgb.jpg/600x600bb.jpg",
        },
        {
            id: 7,
            name: "Creedence Clearwater Revival",
            members: 4,
            genre: "Rock",
            yearFounded: 1967,
            image: "https://is4-ssl.mzstatic.com/image/thumb/Music115/v4/ff/47/e3/ff47e3db-4804-bbbd-afbf-7cf9e0dec02a/00888072355910.rgb.jpg/600x600bb.jpg",
        },
        {
            id: 8,
            name: "The Lumineers",
            members: 3,
            genre: "Folk",
            yearFounded: 2002,
            image: "https://is2-ssl.mzstatic.com/image/thumb/Music114/v4/d9/d7/ee/d9d7ee31-3523-fcac-032b-cd36720d2abd/cover.jpg/600x600bb.jpg",
        },
        {
            id: 9,
            name: "Old Crow Medicine Show",
            members: 6,
            genre: "Bluegrass",
            yearFounded: 1998,
            image: "https://is4-ssl.mzstatic.com/image/thumb/Music/67/77/96/mzi.rorqoofo.jpg/600x600bb.jpg",
        },
        {
            id: 10,
            name: "Lynyrd Skynyrd",
            members: 5,
            genre: "Rock",
            yearFounded: 1964,
            image: "https://is2-ssl.mzstatic.com/image/thumb/Music124/v4/d1/ec/ee/d1ecee5c-1425-1a18-1d68-e9f723d098b5/06UMGIM01482.rgb.jpg/600x600bb.jpg",
        },
        {
            id: 11,
            name: "The Head and the Heart",
            members: 6,
            genre: "Folk",
            yearFounded: 2009,
            image: "https://is4-ssl.mzstatic.com/image/thumb/Music125/v4/f7/05/cc/f705ccf9-d998-60d6-0cd8-1b7b63ddd421/98787091564_1.jpg/600x600bb.jpg",
        },
        {
            id: 12,
            name: "The Grateful Dead",
            members: 6,
            genre: "Rock",
            yearFounded: 1965,
            image: "https://is4-ssl.mzstatic.com/image/thumb/Music124/v4/e9/b6/e2/e9b6e214-1f54-8386-913b-e245fa960ff6/603497920761.jpg/600x600bb.jpg",
        },
        {
            id: 13,
            name: "Nickle Creek",
            members: 3,
            genre: "Bluegrass",
            yearFounded: 1989,
            image: "https://is5-ssl.mzstatic.com/image/thumb/Music/v4/a0/59/12/a0591223-c548-deb0-ba39-277478aecfab/075597955941.jpg/600x600bb.jpg",
        },
        {
            id: 14,
            name: "Tom Petty and the Heartbreakers",
            members: 5,
            genre: "Rock",
            yearFounded: 1976,
            image: "https://is2-ssl.mzstatic.com/image/thumb/Music124/v4/93/93/fa/9393fa7d-e2db-b8d1-752e-ca719aeccff3/093624935735.jpg/600x600bb.jpg",
        },
        {
            id: 15,
            name: "The Civil Wars",
            members: 2,
            genre: "Folk",
            yearFounded: 2008,
            image: "https://is1-ssl.mzstatic.com/image/thumb/Music125/v4/e3/96/af/e396af82-2437-9e1c-28f0-ab71cedcf118/859749486558_cover.jpg/600x600bb.jpg",
        },
        {
            id: 16,
            name: "Stevie Ray Vaughan and Double Trouble",
            members: 3,
            genre: "Rock",
            yearFounded: 1978,
            image: "https://is3-ssl.mzstatic.com/image/thumb/Music125/v4/db/25/b6/db25b60d-8b54-43b3-4e10-6fd6e85a019a/mzi.qkbchvpj.jpg/600x600bb.jpg",
        },
        {
            id: 17,
            name: "Punch Brothers",
            members: 5,
            genre: "Bluegrass",
            yearFounded: 2006,
            image: "https://is4-ssl.mzstatic.com/image/thumb/Music/21/7f/b7/mzi.taiujmos.jpg/600x600bb.jpg",
        },
        {
            id: 18,
            name: "The Black Keys",
            members: 2,
            genre: "Rock",
            yearFounded: 2001,
            image: "https://is1-ssl.mzstatic.com/image/thumb/Music115/v4/55/39/ca/5539caf8-333e-5ad2-06ca-eaf5d84cd264/mzm.nmxwulyo.jpg/600x600bb.jpg",
        },
        {
            id: 19,
            name: "Colter Wall",
            members: 1,
            genre: "Country",
            yearFounded: 1995,
            image: "https://is4-ssl.mzstatic.com/image/thumb/Music124/v4/5b/78/8f/5b788f57-ffdd-10c8-4f79-573006211796/886446389035.jpg/600x600bb.jpg",
        },
        {
            id: 20,
            name: "Sturgil Simpson",
            members: 1,
            genre: "Bluegrass",
            yearFounded: 1978,
            image: "https://is4-ssl.mzstatic.com/image/thumb/Music124/v4/d9/19/58/d919580b-404d-a398-511f-9bef33b97037/195497084135.jpg/600x600bb.jpg",
        }
    ],
    venues: [
        {
            id: 1,
            name: "Starlight Grove Pavilion",
            address: "123 Moonlit Lane, Enchanted Woods, Fantasyland",
            size: 10000,
            maxOccupancy: 500,
            image: "https://www.visitcalifornia.com/sites/visitcalifornia.com/files/VC_HistoricMusicVenues_Stock_ED_D19CGP_1280x640.jpg",
        },
        {
            id: 2,
            name: "Neon Skyline Lounge",
            address: "456 Techno Avenue, Futuristic City, Cyberrealm",
            size: 8000,
            maxOccupancy: 300,
            image: "https://www.phillymag.com/wp-content/uploads/sites/3/2018/11/live-music-concert-venue-philadelphia.jpg",
        },
        {
            id: 3,
            name: "Rustic Harmony Barn",
            address: "789 Serene Valley Road, Tranquil Meadows, Countryside",
            size: 6500,
            maxOccupancy: 200,
            image: "https://www.choicehotels.com/cms/images/choice-hotels/demand-articles/image_top-7-must-see-live-music-venues_header/image_top-7-must-see-live-music-venues_header.jpg",
        },
        {
            id: 4,
            name: "Celestial Jazz Garden",
            address: "101 Starstruck Street, Cosmic Plaza, Galaxia",
            size: 12000,
            maxOccupancy: 800,
            image: "https://www.frommers.com/system/media_items/attachments/000/863/112/s980/RedRAmphVDc.jpg?1536101591",
        },
    ],
    bookings: [
        {
            bandId: 5,
            venueId: 2,
            date: 20231013,
        },
        {
            bandId: 1,
            venueId: 4,
            date: 20230115,
        },
        {
            bandId: 2,
            venueId: 3,
            date: 20230205,
        },
        {
            bandId: 8,
            venueId: 1,
            date: 20230306,
        },
        {
            bandId: 9,
            venueId: 4,
            date: 20230423,
        },
        {
            bandId: 6,
            venueId: 3,
            date: 20230517,
        },
        {
            bandId: 7,
            venueId: 2,
            date: 20230610,
        },
        {
            bandId: 14,
            venueId: 1,
            date: 20230708,
        },
        {
            bandId: 11,
            venueId: 4,
            date: 20230829,
        },
        {
            bandId: 10,
            venueId: 3,
            date: 20230922,
        },
        {
            bandId: 12,
            venueId: 2,
            date: 20231018,
        },
        {
            bandId: 13,
            venueId: 1,
            date: 20231109,
        },
        {
            bandId: 4,
            venueId: 3,
            date: 20231212,
        },
        {
            bandId: 15,
            venueId: 4,
            date: 20230107,
        },
        {
            bandId: 16,
            venueId: 2,
            date: 20230220,
        },
        {
            bandId: 18,
            venueId: 1,
            date: 20230314,
        },
        {
            bandId: 17,
            venueId: 3,
            date: 20230411,
        },
        {
            bandId: 3,
            venueId: 4,
            date: 20230525,
        },
        {
            bandId: 1,
            venueId: 2,
            date: 20230629,
        },
        {
            bandId: 2,
            venueId: 1,
            date: 20230730,
        },
        {
            bandId: 4,
            venueId: 4,
            date: 20230805,
        },
        {
            bandId: 7,
            venueId: 3,
            date: 20230918,
        },
        {
            bandId: 6,
            venueId: 2,
            date: 20231009,
        },
        {
            bandId: 5,
            venueId: 1,
            date: 20231114,
        },
        {
            bandId: 12,
            venueId: 4,
            date: 20231202,
        },
        {
            bandId: 15,
            venueId: 3,
            date: 20230128,
        },
        {
            bandId: 14,
            venueId: 2,
            date: 20230215,
        },
        {
            bandId: 17,
            venueId: 1,
            date: 20230310,
        },
        {
            bandId: 16,
            venueId: 4,
            date: 20230404,
        },
        {
            bandId: 9,
            venueId: 3,
            date: 20230527,
        },
        {
            bandId: 10,
            venueId: 2,
            date: 20230621,
        },
        {
            bandId: 13,
            venueId: 1,
            date: 20230717,
        },
        {
            bandId: 18,
            venueId: 4,
            date: 20230812,
        },
        {
            bandId: 3,
            venueId: 3,
            date: 20230909,
        },
        {
            bandId: 11,
            venueId: 2,
            date: 20231006,
        },
        {
            bandId: 6,
            venueId: 1,
            date: 20231123,
        },
        {
            bandId: 4,
            venueId: 4,
            date: 20231219,
        },
        {
            bandId: 2,
            venueId: 3,
            date: 20230104,
        },
        {
            bandId: 1,
            venueId: 2,
            date: 20230208,
        },
        {
            bandId: 5,
            venueId: 1,
            date: 20230325,
        },
        {
            bandId: 7,
            venueId: 4,
            date: 20230416,
        },
        {
            bandId: 8,
            venueId: 3,
            date: 20230510,
        },
        {
            bandId: 13,
            venueId: 3,
            date: 20230527,
        },
        {
            bandId: 2,
            venueId: 2,
            date: 20230621,
        },
        {
            bandId: 18,
            venueId: 1,
            date: 20230717,
        },
        {
            bandId: 7,
            venueId: 4,
            date: 20230812,
        },
        {
            bandId: 4,
            venueId: 3,
            date: 20230909,
        },
        {
            bandId: 9,
            venueId: 2,
            date: 20231006,
        },
        {
            bandId: 1,
            venueId: 1,
            date: 20231123,
        },
        {
            bandId: 17,
            venueId: 4,
            date: 20231219,
        },
        {
            bandId: 13,
            venueId: 3,
            date: 20230104,
        },
        {
            bandId: 5,
            venueId: 2,
            date: 20230208,
        },
        {
            bandId: 7,
            venueId: 1,
            date: 20230325,
        },
        {
            bandId: 8,
            venueId: 4,
            date: 20230416,
        },
        {
            bandId: 11,
            venueId: 3,
            date: 20230510,
        }        
    ],
    members: [
        { memberId: 1, bandId: 1, firstName: "Mick", lastName: "Jagger", birthYear: 1943, role: "Singer" },
        { memberId: 2, bandId: 1, firstName: "Keith", lastName: "Richards", birthYear: 1943, role: "Guitarist" },
        { memberId: 3, bandId: 1, firstName: "Charlie", lastName: "Watts", birthYear: 1941, role: "Drummer" },
        { memberId: 4, bandId: 1, firstName: "Ronnie", lastName: "Wood", birthYear: 1947, role: "Guitarist" },
        { memberId: 5, bandId: 2, firstName: "Marcus", lastName: "Mumford", birthYear: 1987, role: "Singer, Guitarist, Drummer" },
        { memberId: 6, bandId: 2, firstName: "Ben", lastName: "Lovett", birthYear: 1986, role: "Keyboardist, Accordionist" },
        { memberId: 7, bandId: 2, firstName: "Winston", lastName: "Marshall", birthYear: 1988, role: "Banjoist, Guitarist (formerly)" },
        { memberId: 8, bandId: 2, firstName: "Ted", lastName: "Dwane", birthYear: 1984, role: "Bassist" },
        { memberId: 9, bandId: 3, firstName: "Stevie", lastName: "Nicks", birthYear: 1948, role: "Singer" },
        { memberId: 10, bandId: 3, firstName: "Lindsey", lastName: "Buckingham", birthYear: 1949, role: "Guitarist, Singer" },
        { memberId: 11, bandId: 3, firstName: "Christine", lastName: "McVie", birthYear: 1943, role: "Keyboardist, Singer" },
        { memberId: 12, bandId: 3, firstName: "John", lastName: "McVie", birthYear: 1945, role: "Bassist" },
        { memberId: 13, bandId: 3, firstName: "Mick", lastName: "Fleetwood", birthYear: 1947, role: "Drummer" },
        { memberId: 14, bandId: 4, firstName: "Scott", lastName: "Avett", birthYear: 1976, role: "Singer, Guitarist, Banjoist" },
        { memberId: 15, bandId: 4, firstName: "Seth", lastName: "Avett", birthYear: 1980, role: "Singer, Guitarist, Pianist" },
        { memberId: 16, bandId: 4, firstName: "Bob", lastName: "Crawford", birthYear: 1975, role: "Bassist" },
        { memberId: 17, bandId: 5, firstName: "Glenn", lastName: "Frey", birthYear: 1948, role: "Singer, Guitarist" },
        { memberId: 18, bandId: 5, firstName: "Don", lastName: "Henley", birthYear: 1947, role: "Singer, Drummer" },
        { memberId: 19, bandId: 5, firstName: "Joe", lastName: "Walsh", birthYear: 1947, role: "Guitarist, Singer" },
        { memberId: 20, bandId: 5, firstName: "Timothy B.", lastName: "Schmit", birthYear: 1947, role: "Bassist, Singer" },
        { memberId: 21, bandId: 5, firstName: "Lindsey", lastName: "Buckingham", birthYear: 1949, role: "Guitarist, Singer" },
        { memberId: 22, bandId: 6, firstName: "Alison", lastName: "Krauss", birthYear: 1971, role: "Singer, Fiddler" },
        { memberId: 23, bandId: 6, firstName: "Dan", lastName: "Tyminski", birthYear: 1967, role: "Guitarist, Singer" },
        { memberId: 24, bandId: 6, firstName: "Ron", lastName: "Block", birthYear: 1964, role: "Banjoist, Guitarist" },
        { memberId: 25, bandId: 6, firstName: "Barry", lastName: "Bales", birthYear: 1969, role: "Bassist" },
        { memberId: 26, bandId: 6, firstName: "Jerry", lastName: "Douglas", birthYear: 1956, role: "Dobroist" },
        { memberId: 27, bandId: 7, firstName: "John", lastName: "Fogerty", birthYear: 1945, role: "Singer, Guitarist" },
        { memberId: 28, bandId: 7, firstName: "Tom", lastName: "Fogerty", birthYear: 1941, role: "Guitarist" },
        { memberId: 29, bandId: 7, firstName: "Stu", lastName: "Cook", birthYear: 1945, role: "Bassist" },
        { memberId: 30, bandId: 7, firstName: "Doug", lastName: "Clifford", birthYear: 1945, role: "Drummer" },
        { memberId: 31, bandId: 8, firstName: "Wesley", lastName: "Schultz", birthYear: 1982, role: "Singer, Guitarist" },
        { memberId: 32, bandId: 8, firstName: "Jeremiah", lastName: "Fraites", birthYear: 1985, role: "Drummer, Pianist" },
        { memberId: 33, bandId: 9, firstName: "Ketch", lastName: "Secor", birthYear: 1978, role: "Fiddler, Singer" },
        { memberId: 34, bandId: 9, firstName: "Critter", lastName: "Fuqua", birthYear: 1977, role: "Banjoist, Guitarist" },
        { memberId: 35, bandId: 9, firstName: "Kevin", lastName: "Hayes", birthYear: 1976, role: "Guitjoist, Singer" },
        { memberId: 36, bandId: 9, firstName: "Morgan", lastName: "Jahnig", birthYear: 1982, role: "Bassist" },
        { memberId: 37, bandId: 9, firstName: "Chance", lastName: "McCoy", birthYear: 1986, role: "Guitarist, Fiddler" },
        { memberId: 38, bandId: 10, firstName: "Ronnie", lastName: "Van Zant", birthYear: 1948, role: "Singer" },
        { memberId: 39, bandId: 10, firstName: "Gary", lastName: "Rossington", birthYear: 1951, role: "Guitarist" },
        { memberId: 40, bandId: 10, firstName: "Rickey", lastName: "Medlocke", birthYear: 1950, role: "Guitarist, Drummer" },
        { memberId: 41, bandId: 11, firstName: "Josiah", lastName: "Johnson", birthYear: 1982, role: "Singer, Guitarist" },
        { memberId: 42, bandId: 11, firstName: "Jonathan", lastName: "Russell", birthYear: 1981, role: "Singer, Guitarist" },
        { memberId: 43, bandId: 11, firstName: "Charity Rose", lastName: "Thielen", birthYear: 1986, role: "Singer, Violinist" },
        { memberId: 44, bandId: 11, firstName: "Kenny", lastName: "Hensley", birthYear: 1987, role: "Pianist" },
        { memberId: 45, bandId: 11, firstName: "Tyler", lastName: "Williams", birthYear: 1982, role: "Drummer" },
        { memberId: 46, bandId: 12, firstName: "Jerry", lastName: "Garcia", birthYear: 1942, role: "Singer, Guitarist" },
        { memberId: 47, bandId: 12, firstName: "Bob", lastName: "Weir", birthYear: 1947, role: "Guitarist, Singer" },
        { memberId: 48, bandId: 12, firstName: "Phil", lastName: "Lesh", birthYear: 1940, role: "Bassist" },
        { memberId: 49, bandId: 12, firstName: "Bill", lastName: "Kreutzmann", birthYear: 1946, role: "Drummer" },
        { memberId: 50, bandId: 12, firstName: "Mickey", lastName: "Hart", birthYear: 1943, role: "Drummer" },
        { memberId: 51, bandId: 12, firstName: "Ron", lastName: "McKernan", birthYear: 1945, role: "Keyboardist, Harmonicist" },
        { memberId: 52, bandId: 13, firstName: "Chris", lastName: "Thile", birthYear: 1981, role: "Singer, Mandolinist" },
        { memberId: 53, bandId: 13, firstName: "Sara", lastName: "Watkins", birthYear: 1981, role: "Singer, Fiddler" },
        { memberId: 54, bandId: 13, firstName: "Sean", lastName: "Watkins", birthYear: 1977, role: "Guitarist, Singer" },
        { memberId: 55, bandId: 14, firstName: "Tom", lastName: "Petty", birthYear: 1950, role: "Singer, Guitarist" },
        { memberId: 56, bandId: 14, firstName: "Mike", lastName: "Campbell", birthYear: 1950, role: "Guitarist" },
        { memberId: 57, bandId: 14, firstName: "Benmont", lastName: "Tench", birthYear: 1953, role: "Keyboardist" },
        { memberId: 58, bandId: 14, firstName: "Ron", lastName: "Blair", birthYear: 1948, role: "Bassist" },
        { memberId: 59, bandId: 14, firstName: "Stan", lastName: "Lynch", birthYear: 1955, role: "Drummer" },
        { memberId: 60, bandId: 15, firstName: "Joy", lastName: "Williams", birthYear: 1982, role: "Singer, Pianist, Guitarist" },
        { memberId: 61, bandId: 15, firstName: "John Paul", lastName: "White", birthYear: 1973, role: "Singer, Guitarist" },
        { memberId: 62, bandId: 16, firstName: "Stevie Ray", lastName: "Vaughan", birthYear: 1954, role: "Singer, Guitarist" },
        { memberId: 63, bandId: 16, firstName: "Tommy", lastName: "Shannon", birthYear: 1946, role: "Bassist" },
        { memberId: 64, bandId: 16, firstName: "Chris", lastName: "Layton", birthYear: 1955, role: "Drummer" },
        { memberId: 65, bandId: 17, firstName: "Chris", lastName: "Eldridge", birthYear: 1982, role: "Guitarist" },
        { memberId: 66, bandId: 17, firstName: "Gabe", lastName: "Witcher", birthYear: 1980, role: "Fiddler" },
        { memberId: 67, bandId: 17, firstName: "Noam", lastName: "Pikelny", birthYear: 1981, role: "Banjoist" },
        { memberId: 68, bandId: 17, firstName: "Chris", lastName: "Thile", birthYear: 1981, role: "Mandolinist" },
        { memberId: 69, bandId: 17, firstName: "Paul", lastName: "Kowert", birthYear: 1985, role: "Bassist" },
        { memberId: 70, bandId: 18, firstName: "Dan", lastName: "Auerbach", birthYear: 1979, role: "Singer, Guitarist" },
        { memberId: 71, bandId: 18, firstName: "Patrick", lastName: "Carney", birthYear: 1980, role: "Drummer" },
        { memberId: 72, bandId: 19, firstName: "Colter", lastName: "Wall", birthYear: 1995, role: "Singer" },
        { memberId: 73, bandId: 20, firstName: "Sturgill", lastName: "Simpson", birthYear: 1978, role: "Singer" },
    ]
}

export const getBands = () => {
    return database.bands.map(band => ({...band}))
}

export const getVenues = () => {
    return database.venues.map(venue => ({...venue}))
}

export const getBookings = () => {
    return database.bookings.map(booking => ({...booking}))
}

export const getMembers = () => {
    return database.members.map(member => ({...member}))
}